/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// DojoRank
	/// </summary>
	/// </summary>
	public class DojoRankCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoRank[] DojoRankArray ;

		public DojoRankCollection() : base()
		{
			DojoRankArray = new DojoRank[15];
		}

		public DojoRankCollection(int capacity) : base()
		{
			DojoRankArray = new DojoRank[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoRankArray[index] = (DojoRank) value;
			}
		}

		public DojoRank this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoRankArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoRankArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoRank) value);
		}

		public int Add(DojoRank value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoRankArray.GetUpperBound(0) + 1)
				{
					DojoRank[] tempDojoRankArray = new DojoRank[count * 2];
					Array.Copy(DojoRankArray, tempDojoRankArray, count - 1);
					DojoRankArray = tempDojoRankArray;
				}
				DojoRankArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoRankArray = new DojoRank[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoRank) value);
		}

		public bool Contains(DojoRank value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoRank) value);
		}

		public int IndexOf(DojoRank value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoRankArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoRank) value);
		}

		public void Insert(int index, DojoRank value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoRankArray.GetUpperBound(0) + 1)
				{
					DojoRank[] tempDojoRankArray = new DojoRank[count * 2];
					Array.Copy(DojoRankArray, tempDojoRankArray, count - 1);
					DojoRankArray = tempDojoRankArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoRankArray[x] = DojoRankArray[x - 1];
				DojoRankArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoRank) value);
		}

		public void Remove(DojoRank value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoRank not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoRankArray[x-1] = DojoRankArray[x];
				DojoRankArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoRankArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoRankArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoRankArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoRankArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoRank[] DojoRankArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoRank[] DojoRankArray, int virtualCount)
			{
				this.DojoRankArray = DojoRankArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoRankArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoRank Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoRankArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoRankCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoRankCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoRankCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoRankCollection</returns>
		public DojoRankCollection Clone()
		{
			DojoRankCollection clonedDojoRank = new DojoRankCollection(count);
			lock(this)
			{
				foreach(DojoRank item in this)
					clonedDojoRank.Add(item);
			}
			return clonedDojoRank;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoRank.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoRankCollection from their children.</param>
		public DojoRankCollection Copy(bool isolated)
		{
			DojoRankCollection isolatedCollection = new DojoRankCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoRankArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoRankArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoRankArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoRank Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoRankArray[x].ID == id)
						return DojoRankArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoRankArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

	}
}
