/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// Provides a template to "print" memberships from.
	/// </summary>
	/// </summary>
	public class DojoMembershipTemplateCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoMembershipTemplate[] DojoMembershipTemplateArray ;

		public DojoMembershipTemplateCollection() : base()
		{
			DojoMembershipTemplateArray = new DojoMembershipTemplate[15];
		}

		public DojoMembershipTemplateCollection(int capacity) : base()
		{
			DojoMembershipTemplateArray = new DojoMembershipTemplate[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoMembershipTemplateArray[index] = (DojoMembershipTemplate) value;
			}
		}

		public DojoMembershipTemplate this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoMembershipTemplateArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoMembershipTemplateArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoMembershipTemplate) value);
		}

		public int Add(DojoMembershipTemplate value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoMembershipTemplateArray.GetUpperBound(0) + 1)
				{
					DojoMembershipTemplate[] tempDojoMembershipTemplateArray = new DojoMembershipTemplate[count * 2];
					Array.Copy(DojoMembershipTemplateArray, tempDojoMembershipTemplateArray, count - 1);
					DojoMembershipTemplateArray = tempDojoMembershipTemplateArray;
				}
				DojoMembershipTemplateArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoMembershipTemplateArray = new DojoMembershipTemplate[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoMembershipTemplate) value);
		}

		public bool Contains(DojoMembershipTemplate value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoMembershipTemplate) value);
		}

		public int IndexOf(DojoMembershipTemplate value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoMembershipTemplateArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoMembershipTemplate) value);
		}

		public void Insert(int index, DojoMembershipTemplate value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoMembershipTemplateArray.GetUpperBound(0) + 1)
				{
					DojoMembershipTemplate[] tempDojoMembershipTemplateArray = new DojoMembershipTemplate[count * 2];
					Array.Copy(DojoMembershipTemplateArray, tempDojoMembershipTemplateArray, count - 1);
					DojoMembershipTemplateArray = tempDojoMembershipTemplateArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoMembershipTemplateArray[x] = DojoMembershipTemplateArray[x - 1];
				DojoMembershipTemplateArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoMembershipTemplate) value);
		}

		public void Remove(DojoMembershipTemplate value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoMembershipTemplate not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoMembershipTemplateArray[x-1] = DojoMembershipTemplateArray[x];
				DojoMembershipTemplateArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoMembershipTemplateArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoMembershipTemplateArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoMembershipTemplateArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoMembershipTemplateArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoMembershipTemplate[] DojoMembershipTemplateArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoMembershipTemplate[] DojoMembershipTemplateArray, int virtualCount)
			{
				this.DojoMembershipTemplateArray = DojoMembershipTemplateArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoMembershipTemplateArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoMembershipTemplate Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoMembershipTemplateArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoMembershipTemplateCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoMembershipTemplateCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoMembershipTemplateCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoMembershipTemplateCollection</returns>
		public DojoMembershipTemplateCollection Clone()
		{
			DojoMembershipTemplateCollection clonedDojoMembershipTemplate = new DojoMembershipTemplateCollection(count);
			lock(this)
			{
				foreach(DojoMembershipTemplate item in this)
					clonedDojoMembershipTemplate.Add(item);
			}
			return clonedDojoMembershipTemplate;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoMembershipTemplate.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoMembershipTemplateCollection from their children.</param>
		public DojoMembershipTemplateCollection Copy(bool isolated)
		{
			DojoMembershipTemplateCollection isolatedCollection = new DojoMembershipTemplateCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoMembershipTemplateArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoMembershipTemplateArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoMembershipTemplateArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoMembershipTemplate Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoMembershipTemplateArray[x].ID == id)
						return DojoMembershipTemplateArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoMembershipTemplateArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

	}
}
