/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// Seminar Registration
	/// </summary>
	/// </summary>
	public class DojoSeminarRegistrationCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoSeminarRegistration[] DojoSeminarRegistrationArray ;

		public DojoSeminarRegistrationCollection() : base()
		{
			DojoSeminarRegistrationArray = new DojoSeminarRegistration[15];
		}

		public DojoSeminarRegistrationCollection(int capacity) : base()
		{
			DojoSeminarRegistrationArray = new DojoSeminarRegistration[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoSeminarRegistrationArray[index] = (DojoSeminarRegistration) value;
			}
		}

		public DojoSeminarRegistration this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoSeminarRegistrationArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoSeminarRegistrationArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoSeminarRegistration) value);
		}

		public int Add(DojoSeminarRegistration value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoSeminarRegistrationArray.GetUpperBound(0) + 1)
				{
					DojoSeminarRegistration[] tempDojoSeminarRegistrationArray = new DojoSeminarRegistration[count * 2];
					Array.Copy(DojoSeminarRegistrationArray, tempDojoSeminarRegistrationArray, count - 1);
					DojoSeminarRegistrationArray = tempDojoSeminarRegistrationArray;
				}
				DojoSeminarRegistrationArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoSeminarRegistrationArray = new DojoSeminarRegistration[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoSeminarRegistration) value);
		}

		public bool Contains(DojoSeminarRegistration value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoSeminarRegistration) value);
		}

		public int IndexOf(DojoSeminarRegistration value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoSeminarRegistrationArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoSeminarRegistration) value);
		}

		public void Insert(int index, DojoSeminarRegistration value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoSeminarRegistrationArray.GetUpperBound(0) + 1)
				{
					DojoSeminarRegistration[] tempDojoSeminarRegistrationArray = new DojoSeminarRegistration[count * 2];
					Array.Copy(DojoSeminarRegistrationArray, tempDojoSeminarRegistrationArray, count - 1);
					DojoSeminarRegistrationArray = tempDojoSeminarRegistrationArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoSeminarRegistrationArray[x] = DojoSeminarRegistrationArray[x - 1];
				DojoSeminarRegistrationArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoSeminarRegistration) value);
		}

		public void Remove(DojoSeminarRegistration value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoSeminarRegistration not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoSeminarRegistrationArray[x-1] = DojoSeminarRegistrationArray[x];
				DojoSeminarRegistrationArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoSeminarRegistrationArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoSeminarRegistrationArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoSeminarRegistrationArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoSeminarRegistrationArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoSeminarRegistration[] DojoSeminarRegistrationArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoSeminarRegistration[] DojoSeminarRegistrationArray, int virtualCount)
			{
				this.DojoSeminarRegistrationArray = DojoSeminarRegistrationArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoSeminarRegistrationArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoSeminarRegistration Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoSeminarRegistrationArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoSeminarRegistrationCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoSeminarRegistrationCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoSeminarRegistrationCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoSeminarRegistrationCollection</returns>
		public DojoSeminarRegistrationCollection Clone()
		{
			DojoSeminarRegistrationCollection clonedDojoSeminarRegistration = new DojoSeminarRegistrationCollection(count);
			lock(this)
			{
				foreach(DojoSeminarRegistration item in this)
					clonedDojoSeminarRegistration.Add(item);
			}
			return clonedDojoSeminarRegistration;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoSeminarRegistration.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoSeminarRegistrationCollection from their children.</param>
		public DojoSeminarRegistrationCollection Copy(bool isolated)
		{
			DojoSeminarRegistrationCollection isolatedCollection = new DojoSeminarRegistrationCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoSeminarRegistrationArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoSeminarRegistrationArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoSeminarRegistrationArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoSeminarRegistration Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoSeminarRegistrationArray[x].ID == id)
						return DojoSeminarRegistrationArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoSeminarRegistrationArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

	}
}
