/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// Summary of MyClass
	/// </summary>
	/// </summary>
	public class DojoTestCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoTest[] DojoTestArray ;

		public DojoTestCollection() : base()
		{
			DojoTestArray = new DojoTest[15];
		}

		public DojoTestCollection(int capacity) : base()
		{
			DojoTestArray = new DojoTest[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoTestArray[index] = (DojoTest) value;
			}
		}

		public DojoTest this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoTestArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoTestArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoTest) value);
		}

		public int Add(DojoTest value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoTestArray.GetUpperBound(0) + 1)
				{
					DojoTest[] tempDojoTestArray = new DojoTest[count * 2];
					Array.Copy(DojoTestArray, tempDojoTestArray, count - 1);
					DojoTestArray = tempDojoTestArray;
				}
				DojoTestArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoTestArray = new DojoTest[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoTest) value);
		}

		public bool Contains(DojoTest value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoTest) value);
		}

		public int IndexOf(DojoTest value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoTestArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoTest) value);
		}

		public void Insert(int index, DojoTest value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoTestArray.GetUpperBound(0) + 1)
				{
					DojoTest[] tempDojoTestArray = new DojoTest[count * 2];
					Array.Copy(DojoTestArray, tempDojoTestArray, count - 1);
					DojoTestArray = tempDojoTestArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoTestArray[x] = DojoTestArray[x - 1];
				DojoTestArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoTest) value);
		}

		public void Remove(DojoTest value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoTest not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoTestArray[x-1] = DojoTestArray[x];
				DojoTestArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoTestArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoTestArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoTestArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoTestArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoTest[] DojoTestArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoTest[] DojoTestArray, int virtualCount)
			{
				this.DojoTestArray = DojoTestArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoTestArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoTest Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoTestArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoTestCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoTestCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoTestCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoTestCollection</returns>
		public DojoTestCollection Clone()
		{
			DojoTestCollection clonedDojoTest = new DojoTestCollection(count);
			lock(this)
			{
				foreach(DojoTest item in this)
					clonedDojoTest.Add(item);
			}
			return clonedDojoTest;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoTest.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoTestCollection from their children.</param>
		public DojoTestCollection Copy(bool isolated)
		{
			DojoTestCollection isolatedCollection = new DojoTestCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoTestArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoTestArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoTestArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoTest Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoTestArray[x].ID == id)
						return DojoTestArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoTestArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

	}
}
