/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// DojoMember
	/// </summary>
	/// </summary>
	public class DojoMemberCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoMember[] DojoMemberArray ;

		public DojoMemberCollection() : base()
		{
			DojoMemberArray = new DojoMember[15];
		}

		public DojoMemberCollection(int capacity) : base()
		{
			DojoMemberArray = new DojoMember[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoMemberArray[index] = (DojoMember) value;
			}
		}

		public DojoMember this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoMemberArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoMemberArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoMember) value);
		}

		public int Add(DojoMember value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoMemberArray.GetUpperBound(0) + 1)
				{
					DojoMember[] tempDojoMemberArray = new DojoMember[count * 2];
					Array.Copy(DojoMemberArray, tempDojoMemberArray, count - 1);
					DojoMemberArray = tempDojoMemberArray;
				}
				DojoMemberArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoMemberArray = new DojoMember[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoMember) value);
		}

		public bool Contains(DojoMember value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoMember) value);
		}

		public int IndexOf(DojoMember value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoMemberArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoMember) value);
		}

		public void Insert(int index, DojoMember value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoMemberArray.GetUpperBound(0) + 1)
				{
					DojoMember[] tempDojoMemberArray = new DojoMember[count * 2];
					Array.Copy(DojoMemberArray, tempDojoMemberArray, count - 1);
					DojoMemberArray = tempDojoMemberArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoMemberArray[x] = DojoMemberArray[x - 1];
				DojoMemberArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoMember) value);
		}

		public void Remove(DojoMember value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoMember not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoMemberArray[x-1] = DojoMemberArray[x];
				DojoMemberArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoMemberArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoMemberArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoMemberArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoMemberArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoMember[] DojoMemberArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoMember[] DojoMemberArray, int virtualCount)
			{
				this.DojoMemberArray = DojoMemberArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoMemberArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoMember Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoMemberArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoMemberCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoMemberCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoMemberCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoMemberCollection</returns>
		public DojoMemberCollection Clone()
		{
			DojoMemberCollection clonedDojoMember = new DojoMemberCollection(count);
			lock(this)
			{
				foreach(DojoMember item in this)
					clonedDojoMember.Add(item);
			}
			return clonedDojoMember;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoMember.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoMemberCollection from their children.</param>
		public DojoMemberCollection Copy(bool isolated)
		{
			DojoMemberCollection isolatedCollection = new DojoMemberCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoMemberArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoMemberArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoMemberArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoMember Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoMemberArray[x].ID == id)
						return DojoMemberArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoMemberArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

		//--- Begin Custom Code ---

        public string ToEncodedString(string separator, string lastSeparator)
        {
            System.Text.StringBuilder s = new System.Text.StringBuilder();

            for (int i = 0; i < this.Count; i++)
            {
                if (i > 0)
                {
                    if (this.Count == 2 | this.Count == i + 1)
                        s.Append(lastSeparator);
                    else
                        s.Append(separator);
                }

                s.Append(this[i].UserAccount.UserName);
            }

            return s.ToString();
        }

		//--- End Custom Code ---
	}
}
