/* ********************************************************** *
 * AMNS NitroCast v1.0 Class Collection Object Business Tier    *
 * Autogenerated by NitroCast © 2007 Roy A.E Hodges             *
 * All Rights Reserved                                        *
 * ---------------------------------------------------------- *
 * Source code may not be reproduced or redistributed without *
 * written expressed permission from the author.              *
 * Permission is granted to modify source code by licencee.   *
 * These permissions do not extend to third parties.          *
 * ********************************************************** */

using System;
using System.Collections;

namespace Amns.Tessen
{
	/// <summary>
	/// <summary>
	/// Seminar
	/// </summary>
	/// </summary>
	public class DojoSeminarCollection : IList, ICloneable 
	{
		private int count = 0;
		private DojoSeminar[] DojoSeminarArray ;

		public DojoSeminarCollection() : base()
		{
			DojoSeminarArray = new DojoSeminar[15];
		}

		public DojoSeminarCollection(int capacity) : base()
		{
			DojoSeminarArray = new DojoSeminar[capacity];
		}

		#region IList Implemenation

		public bool IsFixedSize
		{
			get
			{
				return false;
			}
		}

		public bool IsReadOnly
		{
			get
			{
				return false;
			}
		}

		object IList.this[int index]
		{
			get
			{
				return this[index];
			}
			set
			{
				DojoSeminarArray[index] = (DojoSeminar) value;
			}
		}

		public DojoSeminar this[int index]
		{
			get
			{
				lock(this)
				{
					if(index > count - 1)
						throw(new Exception("Index out of bounds."));
					return DojoSeminarArray[index];
				}
			}
			set
			{
				OnCollectionChanged(EventArgs.Empty);
				DojoSeminarArray[index] = value;
			}
		}

		int IList.Add(object value)
		{
			return Add((DojoSeminar) value);
		}

		public int Add(DojoSeminar value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoSeminarArray.GetUpperBound(0) + 1)
				{
					DojoSeminar[] tempDojoSeminarArray = new DojoSeminar[count * 2];
					Array.Copy(DojoSeminarArray, tempDojoSeminarArray, count - 1);
					DojoSeminarArray = tempDojoSeminarArray;
				}
				DojoSeminarArray[count - 1] = value;
			}
			return count -1;
		}

		public void Clear()
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count = 0;
				DojoSeminarArray = new DojoSeminar[15];
			}
		}

		bool IList.Contains(object value)
		{
			return Contains((DojoSeminar) value);
		}

		public bool Contains(DojoSeminar value)
		{
			return IndexOf(value) != -1;
		}

		int IList.IndexOf(object value)
		{
			return IndexOf((DojoSeminar) value);
		}

		public int IndexOf(DojoSeminar value)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoSeminarArray[x].Equals(value))
						return x;
				return -1;
			}
		}

		void IList.Insert(int index, object value)
		{
			Insert(index, (DojoSeminar) value);
		}

		public void Insert(int index, DojoSeminar value)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				count++;
				// Resize the array if the count is greater than the length 
				// of the array.
				if(count > DojoSeminarArray.GetUpperBound(0) + 1)
				{
					DojoSeminar[] tempDojoSeminarArray = new DojoSeminar[count * 2];
					Array.Copy(DojoSeminarArray, tempDojoSeminarArray, count - 1);
					DojoSeminarArray = tempDojoSeminarArray;
				}
				for(int x = index + 1; x == count - 2; x ++)
					DojoSeminarArray[x] = DojoSeminarArray[x - 1];
				DojoSeminarArray[index] = value;
			}
		}

		void IList.Remove(object value)
		{
			Remove((DojoSeminar) value);
		}

		public void Remove(DojoSeminar value)
		{
			OnCollectionChanged(EventArgs.Empty);
			int index = IndexOf(value);
			if(index == -1)
				throw(new Exception("DojoSeminar not found in collection."));
			RemoveAt(index);
		}

		public void RemoveAt(int index)
		{
			OnCollectionChanged(EventArgs.Empty);
			lock(this)
			{
				for(int x = index + 1; x <= count - 1; x++)
					DojoSeminarArray[x-1] = DojoSeminarArray[x];
				DojoSeminarArray[count - 1] = null;
				count--;
			}
		}

		#endregion

		#region ICollection Implementation

		public int Count
		{
			get
			{
				return count;
			}
		}

		public bool IsSynchronized
		{
			get
			{
				return DojoSeminarArray.IsSynchronized;
			}
		}

		public object SyncRoot
		{
			get
			{
				return DojoSeminarArray;
			}
		}

		public void CopyTo(Array array, int index)
		{
			lock(this)
			{
				DojoSeminarArray.CopyTo(array, index);
			}
		}

		#endregion

		#region IEnumerator Implementation

		public Enumerator GetEnumerator()
		{
			return new Enumerator(DojoSeminarArray, count);
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public class Enumerator : IEnumerator
		{
			private DojoSeminar[] DojoSeminarArray;
			private int cursor;
			private int virtualCount;

			public Enumerator(DojoSeminar[] DojoSeminarArray, int virtualCount)
			{
				this.DojoSeminarArray = DojoSeminarArray;
				this.virtualCount = virtualCount;
				cursor = -1;
			}

			public void Reset()
			{
				cursor = -1;
			}

			public bool MoveNext()
			{
				if(cursor < DojoSeminarArray.Length)
					cursor++;
				return(!(cursor == virtualCount));
			}

			public DojoSeminar Current
			{
				get
				{
					if((cursor < 0) || (cursor == virtualCount))
						throw(new InvalidOperationException());
					return DojoSeminarArray[cursor];
				}
			}

			Object IEnumerator.Current
			{
				get
				{
					return Current;
				}
			}
		}

		#endregion

		/// <summary>
		/// Makes a shallow copy of the current DojoSeminarCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoSeminarCollection</returns>
		#region ICloneable Implementation

		object ICloneable.Clone()
		{
			return Clone();
		}

		/// <summary>
		/// Makes a shallow copy of the current DojoSeminarCollection.
		/// as the parent object.
		/// </summary>
		/// <returns>DojoSeminarCollection</returns>
		public DojoSeminarCollection Clone()
		{
			DojoSeminarCollection clonedDojoSeminar = new DojoSeminarCollection(count);
			lock(this)
			{
				foreach(DojoSeminar item in this)
					clonedDojoSeminar.Add(item);
			}
			return clonedDojoSeminar;
		}

		/// <summary>
		/// Makes a deep copy of the current DojoSeminar.
		/// </summary>
		/// <param name="isolation">Placeholders are used to isolate the 
		/// items in the DojoSeminarCollection from their children.</param>
		public DojoSeminarCollection Copy(bool isolated)
		{
			DojoSeminarCollection isolatedCollection = new DojoSeminarCollection(count);

			lock(this)
			{
				if(isolated)
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoSeminarArray[i].NewPlaceHolder());
					}
				}
				else
				{
					for(int i = 0; i < count; i++)
					{
						isolatedCollection.Add(DojoSeminarArray[i].Copy());
					}
				}
			}
			return isolatedCollection;
		}

		#endregion

		#region Events

		public event EventHandler CollectionChanged;

		protected virtual void OnCollectionChanged(EventArgs e)
		{
			if(CollectionChanged != null)
				CollectionChanged(this, e);
		}

		#endregion

		#region Sort Methods

		/// <summary>
		/// Sorts the collection by id.
		/// </summary>
		public void Sort()
		{
			lock(this)
			{
				Array.Sort(DojoSeminarArray, 0, count);
			}
		}

		#endregion

		#region Find Methods

		/// <summary>
		/// Finds a record by ID.
		/// </summary>
		public DojoSeminar Find(int id)
		{
			lock(this)
			{
				for(int x = 0; x < count; x++)
					if(DojoSeminarArray[x].ID == id)
						return DojoSeminarArray[x];
			}
			return null;
		}

		#endregion

		#region ToString() Override Method

		public override string ToString()
		{
			string lineBreak;

			if(System.Web.HttpContext.Current != null)
			lineBreak = "<br />";
			else
			lineBreak = "\r\n";

			System.Text.StringBuilder s = new System.Text.StringBuilder();
			for(int x = 0; x < count; x++)
			{
				if(x != 0)
					s.Append(lineBreak);
				s.Append(DojoSeminarArray[x].ToString());
			}

			return s.ToString();
		}

		#endregion

	}
}
