//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amns.Tessen.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amns.Tessen.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Membership.
        /// </summary>
        internal static string ActiveMembership {
            get {
                return ResourceManager.GetString("ActiveMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Auto Renewals.
        /// </summary>
        internal static string AllowAutoRenewal {
            get {
                return ResourceManager.GetString("AllowAutoRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Guest Purchase.
        /// </summary>
        internal static string AllowGuestPurchase {
            get {
                return ResourceManager.GetString("AllowGuestPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Member Purchase.
        /// </summary>
        internal static string AllowMemberPurchase {
            get {
                return ResourceManager.GetString("AllowMemberPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Member Renewal.
        /// </summary>
        internal static string AllowMemberRenewal {
            get {
                return ResourceManager.GetString("AllowMemberRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classes.
        /// </summary>
        internal static string ClassUnit_Plural {
            get {
                return ResourceManager.GetString("ClassUnit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string ClassUnit_Singular {
            get {
                return ResourceManager.GetString("ClassUnit_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DayUnit_Plural {
            get {
                return ResourceManager.GetString("DayUnit_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string DayUnit_Singular {
            get {
                return ResourceManager.GetString("DayUnit_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit - .
        /// </summary>
        internal static string EditPrefix {
            get {
                return ResourceManager.GetString("EditPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Early Registration.
        /// </summary>
        internal static string FullEarlyRegistration {
            get {
                return ResourceManager.GetString("FullEarlyRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Late Registration.
        /// </summary>
        internal static string FullLateRegistration {
            get {
                return ResourceManager.GetString("FullLateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Registration.
        /// </summary>
        internal static string FullRegistration {
            get {
                return ResourceManager.GetString("FullRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash compiler is ready..
        /// </summary>
        internal static string HashCompileReady {
            get {
                return ResourceManager.GetString("HashCompileReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Hashes are currently compiling {0} of {1} items. Please wait..
        /// </summary>
        internal static string HashCompileWarning {
            get {
                return ResourceManager.GetString("HashCompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal value..
        /// </summary>
        internal static string IllegalValue {
            get {
                return ResourceManager.GetString("IllegalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Email Body.
        /// </summary>
        internal static string InitialEmailBody {
            get {
                return ResourceManager.GetString("InitialEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Email From.
        /// </summary>
        internal static string InitialEmailFrom {
            get {
                return ResourceManager.GetString("InitialEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Rank.
        /// </summary>
        internal static string InitialRank {
            get {
                return ResourceManager.GetString("InitialRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial rank will specify which rank a new member will start at with this membership..
        /// </summary>
        internal static string InitialRankNote {
            get {
                return ResourceManager.GetString("InitialRankNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Role.
        /// </summary>
        internal static string InitialRole {
            get {
                return ResourceManager.GetString("InitialRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initial role is an optional role to grant a new member with this membership..
        /// </summary>
        internal static string InitialRoleNote {
            get {
                return ResourceManager.GetString("InitialRoleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Signin.
        /// </summary>
        internal static string LastSignin {
            get {
                return ResourceManager.GetString("LastSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Age.
        /// </summary>
        internal static string MaximumAge {
            get {
                return ResourceManager.GetString("MaximumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Membership.
        /// </summary>
        internal static string MaximumMemberFor {
            get {
                return ResourceManager.GetString("MaximumMemberFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Rank.
        /// </summary>
        internal static string MaximumRank {
            get {
                return ResourceManager.GetString("MaximumRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the member provided in the build trees; be sure the build trees are loaded..
        /// </summary>
        internal static string MembershipBuilder_CannotFindMember {
            get {
                return ResourceManager.GetString("MembershipBuilder_CannotFindMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d} - {1:d}.
        /// </summary>
        internal static string MembershipDates {
            get {
                return ResourceManager.GetString("MembershipDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberships.
        /// </summary>
        internal static string Memberships {
            get {
                return ResourceManager.GetString("Memberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No memberships are available for {0} at this time..
        /// </summary>
        internal static string Memberships_Empty {
            get {
                return ResourceManager.GetString("Memberships_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Memberships.
        /// </summary>
        internal static string MembershipsAvailable {
            get {
                return ResourceManager.GetString("MembershipsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Memberships.
        /// </summary>
        internal static string MembershipsCurrent {
            get {
                return ResourceManager.GetString("MembershipsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        internal static string MembershipTab {
            get {
                return ResourceManager.GetString("MembershipTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Template 1.
        /// </summary>
        internal static string MembershipTemplate1 {
            get {
                return ResourceManager.GetString("MembershipTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Template 2.
        /// </summary>
        internal static string MembershipTemplate2 {
            get {
                return ResourceManager.GetString("MembershipTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Template 3.
        /// </summary>
        internal static string MembershipTemplate3 {
            get {
                return ResourceManager.GetString("MembershipTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Template 4.
        /// </summary>
        internal static string MembershipTemplate4 {
            get {
                return ResourceManager.GetString("MembershipTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Template 5.
        /// </summary>
        internal static string MembershipTemplate5 {
            get {
                return ResourceManager.GetString("MembershipTemplate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d} - {1:d}.
        /// </summary>
        internal static string MembershipTemplates_DateFormat {
            get {
                return ResourceManager.GetString("MembershipTemplates_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are no available memberships available at this time..
        /// </summary>
        internal static string MembershipTemplates_None {
            get {
                return ResourceManager.GetString("MembershipTemplates_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memberships.
        /// </summary>
        internal static string MembershipTemplates_Title {
            get {
                return ResourceManager.GetString("MembershipTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Since.
        /// </summary>
        internal static string MemberSince {
            get {
                return ResourceManager.GetString("MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d} ({1:f} hrs.).
        /// </summary>
        internal static string MemberSinceFormat {
            get {
                return ResourceManager.GetString("MemberSinceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        internal static string MemberType {
            get {
                return ResourceManager.GetString("MemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age.
        /// </summary>
        internal static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Membership.
        /// </summary>
        internal static string MinimumMemberFor {
            get {
                return ResourceManager.GetString("MinimumMemberFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rank.
        /// </summary>
        internal static string MinimumRank {
            get {
                return ResourceManager.GetString("MinimumRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Members.
        /// </summary>
        internal static string NewMembers {
            get {
                return ResourceManager.GetString("NewMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninety Day Instructors.
        /// </summary>
        internal static string NinetyDayInstructors {
            get {
                return ResourceManager.GetString("NinetyDayInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Memberships.
        /// </summary>
        internal static string NoMemberships {
            get {
                return ResourceManager.GetString("NoMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no memberships available in this package. Your memberships may already be up to date..
        /// </summary>
        internal static string NoMembershipsFriendly {
            get {
                return ResourceManager.GetString("NoMembershipsFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rank Specified.
        /// </summary>
        internal static string NoRankSpecified {
            get {
                return ResourceManager.GetString("NoRankSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order #.
        /// </summary>
        internal static string OrderNum {
            get {
                return ResourceManager.GetString("OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Member.
        /// </summary>
        internal static string ParentMember {
            get {
                return ResourceManager.GetString("ParentMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Template.
        /// </summary>
        internal static string ParentTemplate {
            get {
                return ResourceManager.GetString("ParentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Acct..
        /// </summary>
        internal static string PrimaryAccountTab {
            get {
                return ResourceManager.GetString("PrimaryAccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Member Type.
        /// </summary>
        internal static string PrimaryMemberType {
            get {
                return ResourceManager.GetString("PrimaryMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the member type for the primary member on this template. Only members that have this type will be able to access the template. In addition the Primary Member is primarily responsible for payments. Subtemplates can be used to add more member types..
        /// </summary>
        internal static string PrimaryMemberTypeNote {
            get {
                return ResourceManager.GetString("PrimaryMemberTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string ProrateMembershipAbbreviation {
            get {
                return ResourceManager.GetString("ProrateMembershipAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Prorate).
        /// </summary>
        internal static string ProrateMembershipSuffix {
            get {
                return ResourceManager.GetString("ProrateMembershipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:f} hrs.).
        /// </summary>
        internal static string RankFormat {
            get {
                return ResourceManager.GetString("RankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        internal static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Member.
        /// </summary>
        internal static string RootMember {
            get {
                return ResourceManager.GetString("RootMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f}.
        /// </summary>
        internal static string SemDescOrderLine_Date {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string SemDescOrderLine_Fee {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0}.
        /// </summary>
        internal static string SemDescOrderLine_For {
            get {
                return ResourceManager.GetString("SemDescOrderLine_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string SemDescOrderLine_Head {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Registration Option).
        /// </summary>
        internal static string SemDescOrderLine_Option {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string SemDescOrderLine_Reg {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} at {2:c} per {3}.
        /// </summary>
        internal static string SemDescOrderLine_Units {
            get {
                return ResourceManager.GetString("SemDescOrderLine_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested seminar does not exist..
        /// </summary>
        internal static string SeminarDoesNotExist {
            get {
                return ResourceManager.GetString("SeminarDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not accepting registrations..
        /// </summary>
        internal static string SeminarRegistrationDisabled {
            get {
                return ResourceManager.GetString("SeminarRegistrationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested registration is locked; the session has changed or a payment has been accepted..
        /// </summary>
        internal static string SeminarRegistrationLocked {
            get {
                return ResourceManager.GetString("SeminarRegistrationLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        internal static string StartupMembership {
            get {
                return ResourceManager.GetString("StartupMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string StartupMembershipAbbreviation {
            get {
                return ResourceManager.GetString("StartupMembershipAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Signup.
        /// </summary>
        internal static string StartupMembershipSuffix {
            get {
                return ResourceManager.GetString("StartupMembershipSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in Membership.
        /// </summary>
        internal static string TimeInMembership {
            get {
                return ResourceManager.GetString("TimeInMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} hrs..
        /// </summary>
        internal static string TimeInMembershipFormat {
            get {
                return ResourceManager.GetString("TimeInMembershipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in Rank.
        /// </summary>
        internal static string TimeInRank {
            get {
                return ResourceManager.GetString("TimeInRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} hrs..
        /// </summary>
        internal static string TimeInRankFormat {
            get {
                return ResourceManager.GetString("TimeInRankFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code.
        /// </summary>
        internal static string TreeHash {
            get {
                return ResourceManager.GetString("TreeHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account in use..
        /// </summary>
        internal static string UserAccountInUse {
            get {
                return ResourceManager.GetString("UserAccountInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username not currently used by another memberr, this can be an existing user or enter a username to create..
        /// </summary>
        internal static string UserAccountNotice {
            get {
                return ResourceManager.GetString("UserAccountNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years..
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years old..
        /// </summary>
        internal static string YearsOld {
            get {
                return ResourceManager.GetString("YearsOld", resourceCulture);
            }
        }
    }
}
